[package]
name = "rwaybar"
version = "0.1.0"
authors = ["Daniel De Graaf <code@danieldg.net>"]
edition = "2018"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

[dependencies]
# Basic runtime
bytes = ""
env_logger = ""
futures-util = ""
json = ""
libc = ""
log = ""
once_cell = ""
strfmt = ""
tokio = { version = "1", features = ['rt', 'net', 'signal', 'sync', 'io-util', 'time'] }
toml = ""
xdg = ""

# GUI
cairo-rs = { version = "", features = ['png'] }
pango = ""
pango-sys = "" # for pango_color_parse
pangocairo = ""
#smithay-client-toolkit = { version = "0.13", default-features = false }
smithay-client-toolkit = { git = "https://github.com/Smithay/client-toolkit.git",  default-features = false }
wayland-client = ""
wayland-cursor = ""
wayland-protocols = ""

# Module specific (could be optional deps)
chrono = ""
chrono-tz = ""
dbus = { version = "", features = ['futures'] }
evalexpr = ""
gdk-pixbuf = ""
libpulse-binding = { version = "", features = ['pa_v14'] }
regex = ""
