[package]
name = "rwaybar"
version = "0.1.0"
authors = ["Daniel De Graaf <code@danieldg.net>"]
edition = "2018"

[profile.dev]
panic = 'abort'

[profile.release]
panic = 'abort'

[dependencies]
# Basic runtime
bytes = ""
env_logger = ""
futures-util = ""
json = ""
libc = ""
log = ""
once_cell = ""
strfmt = "=0.1.6"
tokio = { version = "1", features = ['rt', 'net', 'signal', 'sync', 'io-util', 'time'] }
toml = ""
xdg = ""

# GUI
cairo-rs = "0.9"
pango = "0.9"
pango-sys = "0.10" # for pango_color_parse
pangocairo = "0.10"
smithay-client-toolkit = { version = "0.14", default-features = false }
wayland-client = "0.28.5"
wayland-cursor = "0.28"
wayland-protocols = "0.28"

# Module specific (could be optional deps)
chrono = ""
chrono-tz = ""
dbus = { version = "", features = ['futures'] }
evalexpr = ""
gdk-pixbuf = "" # for SVG icons, else we could use image
libpulse-binding = { version = "", features = ['pa_v14'] }
regex = ""
