[package]
name = "rwaybar"
version = "0.1.0"
authors = ["Daniel De Graaf <code@danieldg.net>"]
edition = "2018"

[dependencies]

# Wayland
smithay-client-toolkit = ""
wayland-protocols = ""
wayland-client = ""
wayland-cursor = ""

# Drawing
cairo-rs = { version = "", features = ['png'] }
pangocairo = ""
pango = ""
# Bugfixes in pango
pango-sys = ""
glib = ""

# icons
gdk-pixbuf = ""

# Runtime
calloop = ""
chrono = ""
chrono-tz = ""
env_logger = ""
json = ""
libc = ""
log = ""
strfmt = ""

# TODO
regex = ""
