[package]
name = "rwaybar"
version = "0.1.0"
authors = ["Daniel De Graaf <code@danieldg.net>"]
edition = "2018"
default-run = 'rwaybar'

[profile.dev]
# 400ms frames are more annoying than a bit more work on compile
opt-level = 1
panic = 'abort'

[profile.release]
panic = 'abort'
lto = true

[features]
default = ['pulse', 'dbus']
dbus = []
pulse = ['libpulse-binding']
# This changes the static dependency on libxkbcommon.so to an optional run-time
# dependency, but also changes the wayland-client code to link to the C
# library.  No actual changes in functionality are present.
dlopen = ['smithay-client-toolkit/dlopen']
tools = []

[dependencies]
# Basic runtime
bytes = "*"
async-once-cell = "0.3"
env_logger = "0.9"
futures-channel = { version = "*" }
futures-util = { version = "*", features = ['channel'] }
json = "*"
libc = "*"
log = "*"
memmap2 = "*"
once_cell = "*"
serde = "1"
strfmt = "=0.1.6"
tokio = { version = "1", features = ['rt', 'net', 'signal', 'sync', 'io-util', 'time'] }
toml = "*"
xdg = "*"
xml-rs = "*"

# GUI
png = "0.17"
resvg = { version = "*", default-features = false }
smithay-client-toolkit = { version = "*", default-features = false }
tiny-skia = "*"
ttf-parser = "*"
usvg = { version = "*", default-features = false }
wayland-client = "0.29"
wayland-cursor = "0.29"
wayland-protocols = "0.29"

# Module specific
chrono = "*"
chrono-tz = "*"
evalexpr = "*"
libpulse-binding = { version = "*", features = ['pa_v14'], optional = true }
regex = "1.5"
zbus = { version = "2.0.0-beta", git = "https://gitlab.freedesktop.org/dbus/zbus", default-features = false }

[[bin]]
name = 'font-dump'
required-features = ['tools']
